server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/preset_proto?allowPublicKeyRetrieval=true} # ${환경변수:기본값}
    username: ${db.username:root}
    password: ${db.password:root}
    # Hikari Pool(Connection Pool)
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000

logging:
  level:
    root: debug
    com.zaxxer.hikari: TRACE
