server:
  port: 80

spring:
  config:
    import:
      - classpath:/app/jwt/jwt.yml
      - classpath:/app/cors/cors.yml
      - classpath:/app/password/password.yml

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/preset_proto?allowPublicKeyRetrieval=true} # ${환경변수:기본값}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 100000
      leak-detection-threshold: 2000

  jpa:
    hibernate: # ddl-auto: 기본값 none이니까 안 써도 되는데 그냥 설명해야 하니까 쓴 거.
      ddl-auto: validate # none or validate로 유지(Flyway를 쓰니까.)
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    # DDL -> Flyway
    # DML -> JPA(ddl-auto를 줘 버리면 DDL까지 먹으니까 그렇게 못 하게 하려고 ddl-auto `none`이나 `validate`로 유지)
